"""phase 2: ingest metadata, notes, mailbox state

Revision ID: 0b7c649348bd
Revises: 36dd6ee0cb8f
Create Date: 2026-08-01 14:55:32.458363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7c649348bd'
down_revision: Union[str, Sequence[str], None] = '36dd6ee0cb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox', sa.String(length=255), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mailbox_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailbox_state_mailbox'), ['mailbox'], unique=True)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('graph_message_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_graph_message_id'), ['graph_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_notes_message_id'), ['message_id'], unique=False)

    # The four NOT NULL columns below carry server defaults. Autogenerate
    # omits them, which fails the moment the table already has rows — and by
    # the time this runs in production it will. The defaults are left in place
    # afterwards rather than dropped: they match the model defaults, and they
    # mean a hand-written INSERT during a 10pm debugging session still works.
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('body_clean', sa.Text(), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('source', sa.String(length=16), nullable=False,
                      server_default='graph')
        )
        batch_op.add_column(sa.Column('forwarded_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('form_type', sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column('attachment_count', sa.Integer(), nullable=False,
                      server_default='0')
        )
        batch_op.add_column(
            sa.Column('attachment_names', sa.JSON(), nullable=False,
                      server_default='[]')
        )
        batch_op.create_index(batch_op.f('ix_messages_source'), ['source'], unique=False)
        batch_op.create_foreign_key(
            'fk_messages_created_by_users', 'users', ['created_by'], ['id'],
            ondelete='SET NULL',
        )

    # Existing rows all arrived before Phase 2, so their cleaned body is just
    # the body. Better than leaving them blank and having the classifier see
    # nothing if they're ever re-run.
    op.execute("UPDATE messages SET body_clean = body_text WHERE body_clean = ''")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_created_by_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_source'))
        batch_op.drop_column('attachment_names')
        batch_op.drop_column('attachment_count')
        batch_op.drop_column('form_type')
        batch_op.drop_column('created_by')
        batch_op.drop_column('forwarded_by')
        batch_op.drop_column('source')
        batch_op.drop_column('body_clean')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_message_id'))
        batch_op.drop_index(batch_op.f('ix_notes_graph_message_id'))

    op.drop_table('notes')
    with op.batch_alter_table('mailbox_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailbox_state_mailbox'))

    op.drop_table('mailbox_state')
    # ### end Alembic commands ###
